spring.application.name=NutriRoute

spring.datasource.url=jdbc:mysql://localhost:3306/NutriRoute
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.app.jwtSecret=ThisIsAStrongJwtSecretKeyForNutriRoute2026Application
spring.app.jwtExpirationMs=172800000

Razorpay.key=rzp_test_S060WMnc2eFoWe
Razorpay.secret=4XRX50lBHOXxPQ9Nwlrb6HxU

logging.level.org.springframework.security=INFO
